
package com.example.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BibliothequeServiceImplService", targetNamespace = "http://service.example.com/", wsdlLocation = "http://localhost:1510/ws/Bibliotheque?wsdl")
public class BibliothequeServiceImplService
    extends Service
{

    private final static URL BIBLIOTHEQUESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BIBLIOTHEQUESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName BIBLIOTHEQUESERVICEIMPLSERVICE_QNAME = new QName("http://service.example.com/", "BibliothequeServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1510/ws/Bibliotheque?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BIBLIOTHEQUESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        BIBLIOTHEQUESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public BibliothequeServiceImplService() {
        super(__getWsdlLocation(), BIBLIOTHEQUESERVICEIMPLSERVICE_QNAME);
    }

    public BibliothequeServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BIBLIOTHEQUESERVICEIMPLSERVICE_QNAME, features);
    }

    public BibliothequeServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, BIBLIOTHEQUESERVICEIMPLSERVICE_QNAME);
    }

    public BibliothequeServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BIBLIOTHEQUESERVICEIMPLSERVICE_QNAME, features);
    }

    public BibliothequeServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BibliothequeServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BibliothequeService
     */
    @WebEndpoint(name = "BibliothequeServiceImplPort")
    public BibliothequeService getBibliothequeServiceImplPort() {
        return super.getPort(new QName("http://service.example.com/", "BibliothequeServiceImplPort"), BibliothequeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BibliothequeService
     */
    @WebEndpoint(name = "BibliothequeServiceImplPort")
    public BibliothequeService getBibliothequeServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.example.com/", "BibliothequeServiceImplPort"), BibliothequeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BIBLIOTHEQUESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw BIBLIOTHEQUESERVICEIMPLSERVICE_EXCEPTION;
        }
        return BIBLIOTHEQUESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
