
package com.example.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BibliothequeService", targetNamespace = "http://service.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BibliothequeService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rechercherLivresParAuteur", targetNamespace = "http://service.example.com/", className = "com.example.client.RechercherLivresParAuteur")
    @ResponseWrapper(localName = "rechercherLivresParAuteurResponse", targetNamespace = "http://service.example.com/", className = "com.example.client.RechercherLivresParAuteurResponse")
    @Action(input = "http://service.example.com/BibliothequeService/rechercherLivresParAuteurRequest", output = "http://service.example.com/BibliothequeService/rechercherLivresParAuteurResponse")
    public List<String> rechercherLivresParAuteur(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLivreParISBN", targetNamespace = "http://service.example.com/", className = "com.example.client.GetLivreParISBN")
    @ResponseWrapper(localName = "getLivreParISBNResponse", targetNamespace = "http://service.example.com/", className = "com.example.client.GetLivreParISBNResponse")
    @Action(input = "http://service.example.com/BibliothequeService/getLivreParISBNRequest", output = "http://service.example.com/BibliothequeService/getLivreParISBNResponse")
    public String getLivreParISBN(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajouterLivre", targetNamespace = "http://service.example.com/", className = "com.example.client.AjouterLivre")
    @ResponseWrapper(localName = "ajouterLivreResponse", targetNamespace = "http://service.example.com/", className = "com.example.client.AjouterLivreResponse")
    @Action(input = "http://service.example.com/BibliothequeService/ajouterLivreRequest", output = "http://service.example.com/BibliothequeService/ajouterLivreResponse")
    public String ajouterLivre(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "supprimerLivre", targetNamespace = "http://service.example.com/", className = "com.example.client.SupprimerLivre")
    @ResponseWrapper(localName = "supprimerLivreResponse", targetNamespace = "http://service.example.com/", className = "com.example.client.SupprimerLivreResponse")
    @Action(input = "http://service.example.com/BibliothequeService/supprimerLivreRequest", output = "http://service.example.com/BibliothequeService/supprimerLivreResponse")
    public boolean supprimerLivre(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllLivres", targetNamespace = "http://service.example.com/", className = "com.example.client.GetAllLivres")
    @ResponseWrapper(localName = "getAllLivresResponse", targetNamespace = "http://service.example.com/", className = "com.example.client.GetAllLivresResponse")
    @Action(input = "http://service.example.com/BibliothequeService/getAllLivresRequest", output = "http://service.example.com/BibliothequeService/getAllLivresResponse")
    public List<String> getAllLivres();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mettreAJourLivre", targetNamespace = "http://service.example.com/", className = "com.example.client.MettreAJourLivre")
    @ResponseWrapper(localName = "mettreAJourLivreResponse", targetNamespace = "http://service.example.com/", className = "com.example.client.MettreAJourLivreResponse")
    @Action(input = "http://service.example.com/BibliothequeService/mettreAJourLivreRequest", output = "http://service.example.com/BibliothequeService/mettreAJourLivreResponse")
    public boolean mettreAJourLivre(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

}
